 const fields = [
	'All',
	'Software development',
	'Quality Assurance',
	'Web,Graphic design',
	'Product,Project Management',
	'Hardware design',
	'Other IT',
	'Sales',
	'Administrative',
	'Tourism',
	'Marketing,Advertising',
	'Journalism,PR',
	'Accounting,Bookkeeping',
	'Finance Management',
	'Banking,credit',
	'TV,Radio',
	'Education,training',
	'Legal',
	'Audit,Compliance',
	'Healthcare,Pharmaceutical',
	'Human Resources',
]             
export default fields;