 const fields = [
	'All',
	'Software development',
	'Quality Assurance',
	'Graphic design',
	'Product',
	'Hardware',
	'Other IT',
	'Sales',
	'Administrative',
	'Tourism',
	'Marketing',
	'Journalism,PR',
	'Accounting',
	'Finance Management',
	'Banking,credit',
	'TV',
	'Education',
	'Legal',
	'Audit,Compliance',
	'Healthcare,Pharmaceutical',
	'Human Resources',
]             
export default fields;